export * from './lib/model/game/Tilemap'
export * from './lib/item/Item'
export * from './lib/item/Registry'
export * from './lib/model/game/Player'
export * from './lib/model/game/Geo'
export * from './lib/model/game/ItemInstance'
export * from './lib/model/game/GameState'
export * from './lib/model/game/Messages'
export * from './lib/model/Instance'
import './lib/item/basic/fire';
